### PR TITLE
Added reset and link buttons.

### PR DESCRIPTION
**Pull request by thaggie**
Inspired by this tweet: https://twitter.com/jaffathecake/status/819216558253862913 I thought it'd be cool to be able share compositions via URLs.

I added the reset button as it seemed be be something I kept wanting.

### CODE REVIEW

**Comment by Heydon** [comment]
This looks great, thank you!

But I'd like to have a play with it before merging. Could you make sure the `docs` folder is publishing to https://thaggie.github.io/beadz-drum-machine?

Thanks again — Heydon

**Comment by thaggie** [comment]
I've merged the last PR and published.

**Comment by Heydon** [comment]
Okay, works really nicely. Now just wondering about the link/reset icons? 
image

**Comment by thaggie** [comment]
I don't have the chops to create real icons.

**Comment by Heydon** [comment]
@thaggie No worries, I'll make time to merge it in then do the icon stuff and release. Great work: I was planning on doing URL sharing and your implementation is really nice.

**Comment by thaggie** [comment]
I though that maybe it'd be better not to have the link button but to change it so that it always puts the state in the URL.

I've made the changes and published to https://thaggie.github.io/beadz-drum-machine so you can checkout how it works now.

So persistence is always in the URL for the browser and always local storage for home screen, state is now persisted on change rather than when the user pauses.

If you prefer this I'll create a separate pull request.

**Pull request merged**
